name: "Remove unwanted stuff to free up disk image"
description: "Remove unwanted stuff to free up disk image"
author: "Gerard Braad <me@gbraad.nl>"
runs:
  using: "composite"
  steps:
    - run: |
        df -h

        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /opt/hostedtoolcache/CodeQL

        sudo docker image prune --all --force
        sudo docker builder prune -a            

        sudo swapoff -a
        sudo rm -f /mnt/swapfile

        df -h
      shell: bash